import { FilesetResolver, PoseLandmarker, DrawingUtils } from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.0/vision_bundle.js?module';
const $ = id => document.getElementById(id);
const video=$('video'), canvas=$('overlay'), ctx=canvas.getContext('2d'), start=$('start'), stop=$('stop');
let landmarker, stream, running=false, frame, lastVideoTime=-1, lastSave=0, lastAlert=0, lastMetricAt=0, poorPostureMs=0;
const toast = msg => { const el=$('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),3500); };
function state(name, cls='neutral'){const el=$('cameraState');el.textContent=name;el.className=`badge ${cls}`}
function scorePose(l){const nose=l[0],ls=l[11],rs=l[12],lh=l[23],rh=l[24];if(![nose,ls,rs,lh,rh].every(x=>x?.visibility>.45))return null;const sh={x:(ls.x+rs.x)/2,y:(ls.y+rs.y)/2}, hip={x:(lh.x+rh.x)/2,y:(lh.y+rh.y)/2};const neck=Math.abs(Math.atan2(nose.x-sh.x,nose.y-sh.y)*180/Math.PI);const shoulders=Math.abs(ls.y-rs.y)*100;const torso=Math.abs(Math.atan2(sh.x-hip.x,sh.y-hip.y)*180/Math.PI);return {neck,shoulders,torso,score:Math.max(0,Math.min(100,100-Math.max(0,neck-12)*2.3-shoulders*1.4-Math.max(0,torso-7)*2))};}
function updateRisk(m){const now=performance.now(),delta=lastMetricAt?Math.min(now-lastMetricAt,1000):0;lastMetricAt=now;if(m.score<60)poorPostureMs+=delta;else poorPostureMs=Math.max(0,poorPostureMs-delta*.35);const high=m.score<50||poorPostureMs>=45000,card=$('officeRiskCard');card.className=`risk-card card ${high?'risk':'good'}`;$('officeRisk').textContent=high?'สีแดง · เสี่ยงจากท่านั่ง':'สีเขียว · ความเสี่ยงจากท่านั่งต่ำ';$('riskReason').textContent=high?`ตรวจพบท่าค้าง/โน้มตัวต่อเนื่อง ${Math.round(poorPostureMs/1000)} วินาที — ลุกพักและปรับเก้าอี้/จอภาพ`:'ท่าที่เห็นตอนนี้ใกล้กลางลำตัวและยังไม่พบการค้างในระดับเตือน';}
function update(m){const s=Math.round(m.score),cls=s>=80?'good':s>=60?'caution':'risk';$('score').value=s;$('score').textContent=s;$('score').style.color=`var(--status-${cls})`;$('status').textContent=s>=80?'ท่านั่งดี':s>=60?'เริ่มโน้มตัว':'ควรปรับท่า';$('advice').textContent=s>=80?'รักษาระดับสายตาและไหล่ให้ผ่อนคลาย':s>=60?'ลองยืดหลังและดึงคางเข้าเล็กน้อย':'พักสั้น ๆ แล้วจัดหลังให้ตรง';$('neck').textContent=`${m.neck.toFixed(0)}°`;$('shoulders').textContent=`${m.shoulders.toFixed(1)}%`;$('torso').textContent=`${m.torso.toFixed(0)}°`;state(s>=80?'กำลังติดตาม':s>=60?'ควรระวัง':'ควรปรับท่า',cls);updateRisk(m);}
async function api(url,options){const r=await fetch(url,options);if(!r.ok)throw Error('บันทึกข้อมูลไม่สำเร็จ');return r.json();}
async function save(m){const now=Date.now();if(now-lastSave>30000){lastSave=now;try{await api('/api/samples',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(m)});loadSummary()}catch(e){toast('ไม่สามารถบันทึกลงฐานข้อมูลได้')}}if(m.score<60&&now-lastAlert>120000){lastAlert=now;try{await api('/api/alerts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({severity:'risk',message:'ตรวจพบท่านั่งที่ควรปรับ'})});loadSummary()}catch{}}}
function draw(result){ctx.clearRect(0,0,canvas.width,canvas.height);if(!result.landmarks?.length)return;const d=new DrawingUtils(ctx);d.drawConnectors(result.landmarks[0],PoseLandmarker.POSE_CONNECTIONS,{color:'#5b8def',lineWidth:3});d.drawLandmarks(result.landmarks[0],{color:'#00e5c7',radius:4});}
function loop(){if(!running)return;if(video.currentTime!==lastVideoTime){lastVideoTime=video.currentTime;const result=landmarker.detectForVideo(video,performance.now());draw(result);const m=result.landmarks?.[0]&&scorePose(result.landmarks[0]);if(m){update(m);save(m)}}frame=requestAnimationFrame(loop)}
async function begin(){if(!window.isSecureContext){toast('กรุณาเปิดผ่าน http://localhost:3000 หรือ HTTPS');return}start.disabled=true;state('กำลังโหลด AI');try{const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.0/wasm');landmarker=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task',delegate:'GPU'},runningMode:'VIDEO',numPoses:1});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();canvas.width=video.videoWidth;canvas.height=video.videoHeight;running=true;$('cameraHelp').hidden=true;start.disabled=true;stop.disabled=false;state('กำลังติดตาม','good');loop()}catch(e){console.error(e);state('เริ่มไม่ได้','risk');toast('เปิดกล้องหรือ AI ไม่สำเร็จ โปรดอนุญาตกล้องและลองใหม่');start.disabled=false}}
function end(){running=false;cancelAnimationFrame(frame);stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;ctx.clearRect(0,0,canvas.width,canvas.height);start.disabled=false;stop.disabled=true;$('cameraHelp').hidden=false;lastMetricAt=0;state('หยุดแล้ว');}
async function loadSummary(){try{const d=await api('/api/summary');$('average').textContent=d.average??'--';$('samples').textContent=d.samples??0;$('alerts').textContent=d.alerts.length;const list=$('events');list.innerHTML=d.alerts.length?d.alerts.map(a=>`<li class="event-${a.severity}">${new Date(a.created_at).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})} — ${a.message}</li>`).join(''):'<li>ยังไม่มีการแจ้งเตือนในวันนี้</li>'}catch{toast('เชื่อมต่อฐานข้อมูลไม่ได้ — ตรวจสอบว่า server ทำงานอยู่')}}
start.addEventListener('click',begin);stop.addEventListener('click',end);$('refresh').addEventListener('click',loadSummary);$('clearData').addEventListener('click',async()=>{if(confirm('ลบประวัติและแจ้งเตือนทั้งหมดจากฐานข้อมูลในเครื่อง?')){await api('/api/data',{method:'DELETE'});loadSummary();toast('ลบข้อมูลแล้ว')}});window.addEventListener('beforeunload',end);loadSummary();
